[package]
name = "atropos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
cpal = "0.15.1"
dasp_sample = "0.11.0"
ringbuf = "0.3.2"
